CREATE TABLE `books` (
  `id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE `authors` (
  `id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE `books_authors_rel` 
(
  `id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `book_id` INTEGER NOT NULL,
  `author_id` INTEGER NOT NULL,
  FOREIGN KEY (`book_id`) REFERENCES `books`(`id`) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (`author_id`) REFERENCES `authors`(`id`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;